In [23]:
import pandas as pd


df = pd.read_csv("../data/processed/steam_games_features.csv")


df["name"].duplicated().sum()

np.int64(107)

In [19]:
df[
    [
        "developer_previous_games",
        "developer_previous_success",
        "developer_previous_reception",
    ]
].describe()

,developer_previous_games,developer_previous_success,developer_previous_reception
count,44584.000000,44584.000000,44584.000000
mean,2.344002,0.490189,0.314559
std,6.971430,0.876012,0.387426
min,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000
75%,2.000000,0.666667,0.750000
max,98.000000,3.000000,1.000000

In [24]:
df['name'].duplicated().sum()

np.int64(107)

In [25]:
df[df["name"].duplicated(keep=False)][["name", "release_date", "main_developer"]].head(
    20
)

,name,release_date,main_developer
142,DOOM 3,2007-08-03,id Software
663,Tom Clancy's Splinter Cell Conviction™,2010-04-27,Ubisoft Montreal
669,Tom Clancy's Splinter Cell Conviction™,2010-04-29,Ubisoft Montreal
716,Alter Ego,2010-08-03,bitComposer Games
804,RUSH,2010-12-03,Two Tribes
1116,Yesterday,2012-03-22,Pendulo Studios
1289,DOOM 3,2012-10-15,id Software
1649,Dark Matter,2013-10-17,InterWave Studios
1753,Tank Operations: European Campaign,2013-11-22,Linked Dimensions
2247,Secret Agent,2014-05-05,Apogee Entertainment
2285,Ascendant,2014-05-13,Hapa Games
2329,Stranded,2014-05-20,Peter Moorhead
2386,Lost Marbles,2014-05-30,Binary Takeover
2509,The House,2014-07-01,Konsordo
2681,New York Bus Simulator,2014-08-06,TML-Studios
3135,The Good Life,2014-11-21,immersionFX
3846,Escape,2015-04-20,Stephane Bottin
4298,Nomad,2015-06-26,Diminished Studios
4415,Amygdala,2015-07-15,MachineSpirit
4533,Mystical,2015-07-31,Philippe Forgeur

In [26]:
df[df["main_developer"] == "Valve"][
    ["name", "release_year", "developer_previous_games"]
].head(15)

                               name  release_year  developer_previous_games
2                         Half-Life          1998                         0
3             Team Fortress Classic          1999                         1
5                    Counter-Strike          2000                         2
6                          Ricochet          2000                         3
8                Deathmatch Classic          2001                         4
12                    Day of Defeat          2003                         5
15   Counter-Strike: Condition Zero          2004                         6
16                Half-Life: Source          2004                         7
17           Counter-Strike: Source          2004                         8
18          Half-Life 2: Deathmatch          2004                         9
19                      Half-Life 2          2004                        10
24          Half-Life 2: Lost Coast          2005                        11
31     Half-Life Deathmatch: Source          2006                        12
34         Half-Life 2: Episode One          2006                        13
157                          Portal          2007                        14